-- USER OBJECTS ESTÁN TODOS LOS OBJETOS DE USUARIO
SELECT * FROM USER_OBJECTS
WHERE OBJECT_TYPE='PROCEDURE';

-- CONTADOR DE TODOS LOS TIPOS DE OBJETO DE LA BASE DE DATOS
SELECT OBJECT_TYPE,COUNT(*) FROM USER_OBJECTS
GROUP BY OBJECT_TYPE;

-- MOSTRAR CODIGO FUENTE DE UN PROCEDIMIENTO O FUNCION
SELECT TEXT FROM USER_SOURCE
WHERE NAME='SECURE_DML';